variables:
  AMPL_DEMO_URL: 'https://ampl.com/demo/'
  AMPL_EXT_DEMO_URL: 'https://ampl.com/dl/fdabrandao/demo/'
  LINUX32_BUNDLE_URL: '$(AMPL_DEMO_URL)/ampl.linux32.tgz'
  LINUX64_BUNDLE_URL: '$(AMPL_EXT_DEMO_URL)/ampl.linux64.tgz'
  MACOS64_BUNDLE_URL: '$(AMPL_DEMO_URL)/ampl.macos64.tgz'
  MSWIN32_BUNDLE_URL: '$(AMPL_DEMO_URL)/ampl.mswin32.zip'
  MSWIN64_BUNDLE_NAME: '$(AMPL_DEMO_URL)/ampl.mswin64.zip'
  CTEST_OUTPUT_ON_FAILURE: 1

jobs:
- job: macos_iodbc
  pool: {vmImage: 'macOS-10.15'}
  variables:
    upload: $(Build.ArtifactStagingDirectory)
    AMPL_URL: $(MACOS64_BUNDLE_URL)
  steps:
    - task: UsePythonVersion@0
    - bash: |
        set -x
        sysctl -n machdep.cpu.brand_string
        sysctl -n machdep.cpu.core_count
        sysctl -n machdep.cpu.thread_count
        sysctl -a | grep machdep.cpu
      displayName: Check CPU details
    - bash: bash download-ampl.sh $AMPL_URL
      displayName: Install AMPL
    - bash: |
        set -ex
        export PATH=$PATH:$PWD/ampl/
        brew uninstall --ignore-dependencies unixodbc
        brew install autoconf automake libtool
        curl -sL https://github.com/openlink/iODBC/releases/download/v3.52.15/libiodbc-3.52.15.tar.gz | tar xz
        cd libiodbc-3.52.15
        CFLAGS="-O -arch x86_64"
        CFLAGS="$CFLAGS -mmacosx-version-min=10.9"
        export CFLAGS
        sh autogen.sh
        ./configure \
          --disable-dependency-tracking \
          --prefix=/usr/local/iODBC.universal
        make
        sudo make install
        rm /usr/local/iODBC.universal/lib/libodbc.a
        export PATH=$PATH:/usr/local/iODBC.universal/include:/usr/local/iODBC.universal/lib
        echo $PATH
        cd ..
        git submodule update --init --recursive --remote
        mkdir build
        cd build
        cmake ..
        make all -j2
        ctest
        cpack
      displayName: Build package
    - bash: |
        UPLOAD_DIR=$UPLOAD/macos-iodbc/
        mkdir -p $UPLOAD_DIR
        cp build/tables.zip $UPLOAD_DIR
      displayName: Upload package
    - task: PublishBuildArtifacts@1
      inputs: {pathtoPublish: '$(Build.ArtifactStagingDirectory)'}
