amplsolver:
	cd $${OBJDIR=sys.`uname -m`.`uname -s`}; make

clean:
	cd $${OBJDIR=sys.`uname -m`.`uname -s`}; make clean

veryclean:
	rm -rf $${OBJDIR=sys.`uname -m`.`uname -s`}

distclean:
	rm -rf sys.*.*
