reset;
load amplsqlite3.dll;

model diet.mod;
data diet.dat;

# display the data
display NUTR, FOOD;
display n_min, n_max;
display cost, f_min, f_max;
display amt;

option solver highs;
solve; 

table nutr OUT "amplsqlite3" "diet.db":
	[nutr], n_min, n_max;

table food OUT "amplsqlite3" "diet.db":
	[food], cost, f_min, f_max;

table amt OUT "amplsqlite3" "diet.db":
	[nutr, food], amt;

# write the data
write table nutr;
write table food;
write table amt;
