option solver minos;

option display_precision 0;
model diet.mod;

param dname symbolic := "amplxl";
param fname symbolic := "diet_in_1.xlsx";

table Amounts IN (dname) (fname):
    [NUTR,FOOD], amt;
table Foods IN (dname) (fname):
    FOOD <- [FOOD], cost, f_min, f_max;
table Nutrients IN (dname) (fname):
    NUTR <- [NUTR], n_min, n_max;

read table Foods;
read table Nutrients;
read table Amounts;

display NUTR;
display FOOD;
display amt;

solve;

display {j in FOOD} (Buy[j], Buy.rc[j],  Buy[j]/f_max[j]);
