# test if .xlsx file is generated without being provided in table declaration
reset;
option display_precision 0;

set A := 1..100;
param B{A};
param C{A};

for {i in A}{

	let B[i] := 1/i;
	let C[i] := 2**i;
}

table notdeclared OUT "amplxl":
	[A], B, C;

write table notdeclared;

reset;

set A;
param B{A};
param C{A};

table notdeclared IN "amplxl":
	A <- [A], B, C;

read table notdeclared;

display A;
display B;
display C;

