reset;

model diet.mod;

table nutr INOUT "amplsqlite3" "diet.db":
	NUTR <- [nutr], n_min, n_max;

table food INOUT "amplsqlite3" "diet.db":
	FOOD <- [food], cost, f_min, f_max;

table amt INOUT "amplsqlite3" "diet.db":
	[nutr, food], amt;

# read the data
read table nutr;
read table food;
read table amt;

# display the data
display NUTR, FOOD;
display n_min, n_max;
display cost, f_min, f_max;
display amt;

let n_min["A"] := 600;
let n_max["C"] := 11000;

let cost["MCH"] := 10000;
let f_min["FISH"] := 10;
let f_max["HAM"] := 110;

let amt["B1", "MTL"] := 10000;

display NUTR, FOOD;
display n_min, n_max;
display cost, f_min, f_max;
display amt;

# write the data
write table nutr;
write table food;
write table amt;

print "diet_update done";
