reset;

model diet.mod;

table nutr IN "amplsqlite3" "diet.db":
	NUTR <- [nutr], n_min, n_max;

table food IN "amplsqlite3" "diet.db":
	FOOD <- [food], cost, f_min, f_max;

table amt IN "amplsqlite3" "diet.db":
	[nutr, food], amt;

# read the data
read table nutr;
read table food;
read table amt;

# display the data
display NUTR, FOOD;
display n_min, n_max;
display cost, f_min, f_max;
display amt;

print "diet_read_update done";
