# read table filled with -1 values 
reset;
set A := {"1", 1, "2", 2};
set B := {"3", 3, "4", 4, "5", 5};
set C := {"6", 6, "7", 7, "8", 8, "9", 9};

param D{A,B,C} symbolic;

table test IN "amplxl" "2D" "keyvaltest2D1.xlsx":
	[A, B, C], D;

read table test;

# add some numeric and symbolic values
let D["1", "3", "6"] := 11111;
let D[1, 3, 6] := "11111";

let D["1", 3, "6"] := "22222";
let D[1, "3", 6] := 22222;

let D["2", "5", "9"] := "33333";
let D[2, 5, 9] := 33333;

# save modifications
table temp OUT "amplxl" "test" "2D" "keyvaltest2D1.xlsx":
	[A, B, C], D;

write table temp;

# load back and display data
reset;
set A := {"1", 1, "2", 2};
set B := {"3", 3, "4", 4, "5", 5};
set C := {"6", 6, "7", 7, "8", 8, "9", 9};

param D{A,B,C} symbolic;

table test IN "amplxl" "2D" "keyvaltest2D1.xlsx":
	[A, B, C], D;

read table test;

display D;
