reset;

param n := 2;
param m := 3;

set A := 1..n;
set B := 1..m;

param C{A,B};
param temp default n * m;

for {i in A, j in B}{
	let C[i,j] := temp;
	let temp := temp - 1;
}

table table2 OUT "amplxl" "shrinkrows2.xlsx":
	[A, B], C;

write table table2;

reset;

param n := 2;
param m := 3;

set A := 1..n;
set B := 1..m;

param C{A,B};

table table2 IN "amplxl" "shrinkrows2.xlsx":
	[A, B], C;

read table table2;

display C;

